### ISSUE TITLE
`.isel_points()` method no longer in xarray

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/impactlab-tools#451]
We use the `isel_points()` method. This method has been dropped from xarray as of v0.13.0 (deprecated since v0.10.0).

Travis CI caught this and it's failing my PR tests because of it. 👎 

See https://xarray.pydata.org/en/stable/whats-new.html#v0-13-0-17-sep-2019 and https://xarray.pydata.org/en/stable/indexing.html#vectorized-indexing for a work around.

**Comment by brews** [comment]
...and this is a problem because risingverse packages require xarray v0.9.0 and the deprecation only comes around with v0.10.0.

Will have to see what's holding up the risingverse from using xarray > v0.9.

**Comment by jrising** [comment]
It sounds like this would be a non-breaking change, but we cam also define a version X milestone, where version X includes bringing packages up to date and moving to python 3.

**Comment by brews** [comment]
Thats a good thought. Up to now, most of the package upgrades have been trivial fixes (e.g. numpy).

This xarray upgrade is trivial in this package but it creates problems in other projection system packages.

I played with this last night and this upgrade might be harder. I've had to pin xarray to v0.9 because newer versions run into trouble with open-estimate's FastDataArray (https://github.com/ClimateImpactLab/open-estimate/blob/f401ad8be8e58e3ae9cd6651be1b466ef4318ff7/openest/generate/fast_dataset.py#L144). It it throws an error in impact-calculations/generate/weather.py whenever we do `allds = xr.Dataset({'region': self.regions})`. It trips when creating the `Dataset` because it cannot do a deep copy of `self.regions`, which is a `FastDataArray` instance.

@jrising, what is `FastDataArray` for exactly? I think need a bit more context before I can fix this. What problem does it solve?

**Comment by jrising** [comment]
Exactly the one you might think: `xarray` (or at least the previous version of it) was way too slow for our purposes. So `FastDataArray` is a drop-in replacement for `xarray.DataArray`.

I'm not sure why `xarray` is so slow: granted, it has a lazy-evaluation system, but resolving that takes much longer than the equivalent operations with `numpy` arrays. Even requesting the `numpy` array from a `DataArray` object takes a considerable fraction of a millisecond. When I switched from `numpy` arrays within `WeatherSlice` to `xarray`, calculations took ~ 10x longer, and I couldn't have that.

**Comment by brews** [comment]
Looks like this immediate issue deal with unit tests in the package. I can easily work around this.
