### ISSUE TITLE
Paralog to also log stderr 

### ISSUE THREAD

**Issue by emileten** [ClimateImpactLab/impactlab-tools#463]
Hey @jrising. I am following up on our conversation on reporting errors to users when running https://gitlab.com/ClimateImpactLab/Impacts/impact-calculations/-/blob/master/generate.sh. One item we had mentioned was the logging of errors. 

I think a first simple improvement would be to make `paralog` log the `stderr` along with the `stdout` -- it only does the latter so far. With the latter code, in the case of multiple processes there isn't, at the moment, much to rely on to understand what kind of errors happen, I think, hence I thought this could be an improvement. 

My suggestion of implementation is as easy as adding :  

```
self.sys_stderr = sys.stderr 
sys.stderr = DoubleLogger(self.logpath)
```

in `paralog.StatusManager.__init__`. This would systematically let the manager log `stderr` in the same log files. We could also think of an implementation allowing for a different log file for errors. 

What do you think ? 

Thanks !

**Comment by jrising** [comment]
I totally agree that we want to log `stderr` to the paralog file. But I'm pretty sure that your solution won't work properly-- while it seems like multiple append file pointers in python don't clobber each other, you would have to add lots of flush calls to get everything in the right order.

What should work, though, is to create one DoubleLogger that you set to both `sys.stdout` and `sys.stderr`. Then calls to write to both of those will get passed to the Logger.

It wouldn't maintain how they get written back to the terminal-- currently, DoubleLogger always writes to `sys.stdout`. I think that's fine. But if you wanted to keep things totally proper, you would split DoubleLogger to a parent class (which logs to the file), and instantiate two child classes-- for the two output streams-- which would pass data up to their parent while also writing the same data out to that child's specific output stream.

**Comment by emileten** [comment]
@jrising thanks for the feed back ! 

Working in https://github.com/emileten/impactlab-tools/tree/exception-logger which implements something different but also useful for https://gitlab.com/ClimateImpactLab/Impacts/impact-calculations/-/issues/191 which was the initial goal.
